packages:
  - apps/*
  - components/*
  - frameworks/*
  - libraries/*
  - plugins/*
  - presets/*
  - react/*
  - solid/*
  - tools/*
allowBuilds:
  core-js: true
  core-js-pure: true
  esbuild: true
  fsevents: true
  puppeteer: true
overrides:
  '@babel/plugin-syntax-import-attributes': 7.24.7
