ignores:
  - "@babel/plugin-syntax-flow"
  - "@babel/plugin-transform-react-jsx"
  - "@storybook/*"
  - "@testing-library/*"
  - babel-loader
  - fuse.js
  - identity-obj-proxy
  - npm-check-updates
  - postcss-loader
  - react
  - react-dom
  - solid-command-palette
  - solid-transition-group
  - tinykeys
  - webpack
